language: rust
before_install:
  # evm
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

  # cask
  - curl -fsSkL https://raw.github.com/dajva/cask/master/go | python
  - export PATH=$HOME/.cask/bin:$PATH
  - cask

  # ripgrep
  - cargo install ripgrep
  - export PATH=$HOME/.cargo/bin:$PATH
env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
install:
  - make deps
script:
  - emacs --version
  - make test
