name: Build
on:
  push:
  release:
    types:
      - created
  pull_request:
  schedule:
    - cron: '0 6 1 * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.1
          - 26.3
          - 27.2
          - 28.2
          - 29.1
          - 29.4
          - 30.1
          - 30.2
    steps:
    - name: Setup emacs-ci-nix for ${{ matrix.emacs_version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Setup Cask
      uses: conao3/setup-cask@master

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install ripgrep
      env:
        REPO: BurntSushi/ripgrep
      run: |
        RELEASE_TAG=$(curl -sL --fail \
        -H 'Accept: application/vnd.github.v3+json' \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        'https://api.github.com/repos/BurntSushi/ripgrep/releases/latest' \
        | jq -r '.name')

        PACKAGE_NAME=ripgrep-${RELEASE_TAG}-x86_64-unknown-linux-musl.tar.gz

        curl -sL --fail  \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/${REPO}/releases/tags/${RELEASE_TAG}" \
        | jq -r ".assets | .[] | select(.name==\"${PACKAGE_NAME}\") | .url" \
        | tee asset.url

        curl -sL --fail \
        -H "Accept: application/octet-stream" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -o "${PACKAGE_NAME}" \
        "$(cat asset.url)"
        tar xf ${PACKAGE_NAME}
        echo "$PWD/$(basename -s .tar.gz $PACKAGE_NAME)" >> $GITHUB_PATH

    - name: Install emacs deps
      run: make EMACS_VERSION=${{ matrix.emacs_version }} deps

    - name: Run tests
      run: |
        emacs --version
        rg --version
        make EMACS_VERSION=${{ matrix.emacs_version }} test

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: emacs-${{ matrix.emacs_version }}
        parallel: true

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

